# Generated by Django 4.2.21 on 2025-05-24 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TexiApp', '0002_customuser_mode_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Default to current time if not provided'),
        ),
    ]
