# Generated by Django 4.2.21 on 2025-05-24 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TexiApp', '0003_ride_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mode',
            field=models.CharField(blank=True, choices=[('driver', 'Driver'), ('passenger', 'Passenger')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
