# Generated by Django 4.2.21 on 2025-05-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TexiApp', '0004_alter_customuser_mode_alter_ride_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dropoff_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='dropoff_lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_lng',
            field=models.FloatField(),
        ),
    ]
