# Generated by Django 4.2.21 on 2025-05-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TexiApp', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='matched_ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='TexiApp.ride'),
        ),
    ]
