# Generated by Django 4.2.21 on 2025-05-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TexiApp', '0008_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='TexiApp.ride'),
        ),
    ]
