# Generated by Django 4.2.21 on 2025-05-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TexiApp', '0010_remove_message_ride_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_type',
            field=models.CharField(choices=[('request', 'Ride Request'), ('offer', 'Ride Offer'), ('parcel', 'Parcel Delivery')], max_length=10),
        ),
    ]
