# Generated by Django 4.2.21 on 2025-05-31 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TexiApp', '0011_alter_ride_ride_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='is_active',
            new_name='_is_active',
        ),
        migrations.AddField(
            model_name='ride',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
