# Generated by Django 4.2.21 on 2025-06-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TexiApp', '0012_alter_ride_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
