# Generated by Django 4.2.21 on 2025-06-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TexiApp', '0016_alter_ride_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
